name = "RegisterPenalty"
uuid = "464fa2a9-b19c-5c59-8698-f58c971f971e"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.3.0"

[deps]
CachedInterpolations = "b9709bfb-d23d-5560-8276-8c35c4b76823"
CenterIndexedArrays = "46a7138f-0d70-54e1-8ada-fb8296f91f24"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RegisterCore = "67712758-55e7-5c3c-8e85-dda1d7758434"
RegisterDeformation = "c19381b7-cf49-59d7-881c-50dfbd227eaf"
RegisterUtilities = "d4862ba2-f42c-5aeb-af4f-96a8884a16c4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CachedInterpolations = "0.1"
CenterIndexedArrays = "0.1, 0.2"
CoordinateTransformations = "0.5"
Interpolations = "0.9, 0.10, 0.11, 0.12, 0.13"
RegisterCore = "0.2.1"
RegisterDeformation = "0.3, 0.4"
RegisterUtilities = "0.1"
StaticArrays = "0.10, 0.11, 0.12"
julia = "1.6"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "Test"]
